// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // ignore_for_file: type=lint,unused_import

// GENERATED BY drift_dev, DO NOT MODIFY.
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    teams,
    events,
    members,
    reports,
    ratios,
    collectReportEvents,
    eventTransactions,
  ];
  late final Shape0 teams = Shape0(
    source: i0.VersionedTable(
      entityName: 'teams',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 events = Shape1(
    source: i0.VersionedTable(
      entityName: 'events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_4,
        _column_5,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 members = Shape2(
    source: i0.VersionedTable(
      entityName: 'members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_6, _column_2, _column_7, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 reports = Shape3(
    source: i0.VersionedTable(
      entityName: 'reports',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_8,
        _column_2,
        _column_9,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 ratios = Shape4(
    source: i0.VersionedTable(
      entityName: 'ratios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_10, _column_4, _column_11, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 collectReportEvents = Shape5(
    source: i0.VersionedTable(
      entityName: 'collect_report_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_12, _column_13, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 eventTransactions = Shape6(
    source: i0.VersionedTable(
      entityName: 'event_transactions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_2,
        _column_14,
        _column_15,
        _column_12,
        _column_5,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'PRIMARY KEY AUTOINCREMENT',
      ),
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'description',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<DateTime> _column_3(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'create_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
      defaultValue: const CustomExpression('strftime(\'%s\', CURRENT_DATE)'),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get teamID =>
      columnsByName['team_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get date =>
      columnsByName['date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'team_i_d',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES teams (id) ON DELETE CASCADE',
      ),
    );
i1.GeneratedColumn<DateTime> _column_5(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'date',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
      defaultValue: const CustomExpression('strftime(\'%s\', CURRENT_DATE)'),
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get joinAt =>
      columnsByName['join_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<DateTime> _column_7(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'join_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get generateFor =>
      columnsByName['generate_for']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
    );
i1.GeneratedColumn<DateTime> _column_9(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'generate_for',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
      defaultValue: const CustomExpression('strftime(\'%s\', CURRENT_DATE)'),
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get memberID =>
      columnsByName['member_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get teamID =>
      columnsByName['team_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get ratio =>
      columnsByName['ratio']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'member_i_d',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES members (id) ON DELETE CASCADE',
      ),
    );
i1.GeneratedColumn<double> _column_11(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'ratio',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get eventID =>
      columnsByName['event_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reportID =>
      columnsByName['report_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'event_i_d',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES events (id) ON DELETE CASCADE',
      ),
    );
i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'report_i_d',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES reports (id) ON DELETE CASCADE',
      ),
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get transactionType =>
      columnsByName['transaction_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get eventID =>
      columnsByName['event_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get date =>
      columnsByName['date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<double> _column_14(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'amount',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'transaction_type',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    teams,
    events,
    members,
    reports,
    ratios,
    collectReportEvents,
    eventTransactions,
    eventRatios,
  ];
  late final Shape0 teams = Shape0(
    source: i0.VersionedTable(
      entityName: 'teams',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_2, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 events = Shape1(
    source: i0.VersionedTable(
      entityName: 'events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_4,
        _column_5,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 members = Shape2(
    source: i0.VersionedTable(
      entityName: 'members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_6, _column_2, _column_7, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 reports = Shape3(
    source: i0.VersionedTable(
      entityName: 'reports',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_8,
        _column_2,
        _column_9,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 ratios = Shape4(
    source: i0.VersionedTable(
      entityName: 'ratios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_10, _column_4, _column_11, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 collectReportEvents = Shape5(
    source: i0.VersionedTable(
      entityName: 'collect_report_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_12, _column_13, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 eventTransactions = Shape6(
    source: i0.VersionedTable(
      entityName: 'event_transactions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_2,
        _column_14,
        _column_15,
        _column_12,
        _column_5,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 eventRatios = Shape7(
    source: i0.VersionedTable(
      entityName: 'event_ratios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_10, _column_12, _column_11, _column_3],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get memberID =>
      columnsByName['member_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get eventID =>
      columnsByName['event_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get ratio =>
      columnsByName['ratio']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
}

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    teams,
    events,
    members,
    reports,
    ratios,
    collectReportEvents,
    guests,
    eventTransactions,
    eventRatios,
    menus,
    eventOrders,
  ];
  late final Shape8 teams = Shape8(
    source: i0.VersionedTable(
      entityName: 'teams',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 events = Shape9(
    source: i0.VersionedTable(
      entityName: 'events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_4,
        _column_5,
        _column_3,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 members = Shape10(
    source: i0.VersionedTable(
      entityName: 'members',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_6,
        _column_2,
        _column_7,
        _column_17,
        _column_18,
        _column_19,
        _column_3,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 reports = Shape11(
    source: i0.VersionedTable(
      entityName: 'reports',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_1,
        _column_8,
        _column_2,
        _column_9,
        _column_3,
        _column_16,
        _column_17,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 ratios = Shape12(
    source: i0.VersionedTable(
      entityName: 'ratios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_10,
        _column_4,
        _column_11,
        _column_3,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 collectReportEvents = Shape13(
    source: i0.VersionedTable(
      entityName: 'collect_report_events',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_12, _column_13, _column_3, _column_16],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 guests = Shape14(
    source: i0.VersionedTable(
      entityName: 'guests',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_6,
        _column_2,
        _column_19,
        _column_3,
        _column_16,
        _column_17,
        _column_20,
        _column_21,
        _column_22,
        _column_18,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 eventTransactions = Shape15(
    source: i0.VersionedTable(
      entityName: 'event_transactions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_2,
        _column_14,
        _column_15,
        _column_12,
        _column_5,
        _column_3,
        _column_16,
        _column_23,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 eventRatios = Shape16(
    source: i0.VersionedTable(
      entityName: 'event_ratios',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_10,
        _column_12,
        _column_11,
        _column_3,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 menus = Shape17(
    source: i0.VersionedTable(
      entityName: 'menus',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [_column_0, _column_1, _column_3, _column_16, _column_17],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 eventOrders = Shape18(
    source: i0.VersionedTable(
      entityName: 'event_orders',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_0,
        _column_23,
        _column_26,
        _column_12,
        _column_27,
        _column_28,
        _column_3,
        _column_16,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<bool> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<bool>;
}

i1.GeneratedColumn<DateTime> _column_16(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'modified_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.dateTime,
      defaultValue: const CustomExpression('strftime(\'%s\', CURRENT_DATE)'),
    );
i1.GeneratedColumn<bool> _column_17(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'is_active',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("is_active" IN (0, 1))',
      ),
      defaultValue: const CustomExpression('1'),
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get teamID =>
      columnsByName['team_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get date =>
      columnsByName['date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<bool> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<bool>;
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get joinAt =>
      columnsByName['join_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<bool> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<DateTime> get birthday =>
      columnsByName['birthday']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<String> get profileImage =>
      columnsByName['profile_image']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<DateTime> _column_18(String aliasedName) =>
    i1.GeneratedColumn<DateTime>(
      'birthday',
      aliasedName,
      true,
      type: i1.DriftSqlType.dateTime,
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'profile_image',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get generateFor =>
      columnsByName['generate_for']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<bool> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<bool>;
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get memberID =>
      columnsByName['member_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get teamID =>
      columnsByName['team_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get ratio =>
      columnsByName['ratio']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<DateTime>;
}

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get eventID =>
      columnsByName['event_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reportID =>
      columnsByName['report_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<DateTime>;
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get profileImage =>
      columnsByName['profile_image']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<bool> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get telegramId =>
      columnsByName['telegram_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get instagramId =>
      columnsByName['instagram_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get phoneNumber =>
      columnsByName['phone_number']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get birthday =>
      columnsByName['birthday']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'telegram_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'instagram_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'phone_number',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get description =>
      columnsByName['description']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get transactionType =>
      columnsByName['transaction_type']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get eventID =>
      columnsByName['event_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<DateTime> get date =>
      columnsByName['date']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<int> get memberID =>
      columnsByName['member_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get guestID =>
      columnsByName['guest_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get attachment =>
      columnsByName['attachment']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'member_i_d',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES members (id) ON DELETE CASCADE',
      ),
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'guest_i_d',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES guests (id) ON DELETE CASCADE',
      ),
    );
i1.GeneratedColumn<String> _column_25(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'attachment',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get memberID =>
      columnsByName['member_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get eventID =>
      columnsByName['event_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<double> get ratio =>
      columnsByName['ratio']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<DateTime>;
}

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<bool> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<bool>;
}

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get memberID =>
      columnsByName['member_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get guessID =>
      columnsByName['guess_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get eventID =>
      columnsByName['event_i_d']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<bool> get isDelivered =>
      columnsByName['is_delivered']! as i1.GeneratedColumn<bool>;
  i1.GeneratedColumn<String> get menuItems =>
      columnsByName['menu_items']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<DateTime> get createAt =>
      columnsByName['create_at']! as i1.GeneratedColumn<DateTime>;
  i1.GeneratedColumn<DateTime> get modifiedAt =>
      columnsByName['modified_at']! as i1.GeneratedColumn<DateTime>;
}

i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'guess_i_d',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'REFERENCES guests (id) ON DELETE CASCADE',
      ),
    );
i1.GeneratedColumn<bool> _column_27(String aliasedName) =>
    i1.GeneratedColumn<bool>(
      'is_delivered',
      aliasedName,
      false,
      type: i1.DriftSqlType.bool,
      defaultConstraints: i1.GeneratedColumn.constraintIsAlways(
        'CHECK ("is_delivered" IN (0, 1))',
      ),
      defaultValue: const CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'menu_items',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
  ),
);
